@startuml
:Guest: as guest
:User: as user
:BlockedUser: as blocked_user
:Chat Admin: as admin



(Login) as login
(Register) as register
(Logoff) as logoff
(Create chat) as cchat
(Update chat) as uchat
(Delete chat) as dchat
(Block user) as buser
(Add user in chat) as auser
(Get info about chat) as info
(Send message) as send_message
(Exit from chat) as exit



guest-->login
login --> user
guest-->register
cchat --> admin

user -d-> logoff
user -d-> cchat
user -d-> info
user -d-> send_message
user -d-> exit
'user -d->
'user -d->


admin -u-> uchat
admin -u-> dchat
admin -u-> buser
admin -u-> auser
'admin -u->
'admin -u->

@enduml

