@startuml
title Precedents DIAG

:Guest: as guest
:User: as user
:Chat Admin: as admin

left to right direction

rectangle "Autorization"{
    usecase "Login" as login
    usecase "Register" as register
    usecase "Logout" as logoff
}

rectangle "Message"{
(Send message) as send_message

}


rectangle "Chat"{
(Get info about chat) as info
(Exit from chat) as exit
(Create chat) as cchat
(Update chat) as uchat
(Delete chat) as dchat
(Add user in chat) as auser
(Get messages history) as history
}

guest-->login
guest-->register


user --> logoff
user --> cchat
user --> info
user --> send_message
user --> exit
user --> history


admin --> uchat
admin --> dchat
admin --> auser


@enduml

